/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx}', './*.html'],
  safelist: [
    'px-margin-mobile', 'px-margin-desktop', 'py-section-gap', 'pb-section-gap', 'pt-section-gap',
    'max-w-container-max', 'gap-gutter', 'gap-element-gap',
    'md:px-margin-desktop', 'md:col-span-2', 'md:col-span-3', 'md:col-span-4',
    'md:col-span-5', 'md:col-span-7', 'md:col-span-8', 'md:col-span-12',
    'lg:col-span-2', 'lg:col-span-3', 'lg:col-span-4', 'lg:col-span-5',
    'lg:col-span-7', 'lg:col-span-8', 'lg:col-span-12',
    'md:grid-cols-2', 'md:grid-cols-3', 'md:grid-cols-4', 'md:grid-cols-12',
    'lg:grid-cols-2', 'lg:grid-cols-3', 'lg:grid-cols-12',
    'md:col-span-2', 'md:mt-12', 'lg:mt-12',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#795950',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-tertiary': '#ffffff',
        'surface': '#fcf9f8',
        'on-secondary-fixed-variant': '#5d4037',
        'inverse-primary': '#c8c6c3',
        'secondary-fixed-dim': '#e7bdb1',
        'surface-tint': '#5e5e5c',
        'on-surface-variant': '#454742',
        'on-error-container': '#93000a',
        'outline-variant': '#c6c7c0',
        'primary': '#5e5e5c',
        'on-primary-fixed': '#1b1c1a',
        'primary-fixed-dim': '#c8c6c3',
        'on-primary-container': '#747471',
        'inverse-surface': '#303030',
        'primary-fixed': '#e4e2de',
        'on-surface': '#1b1c1c',
        'outline': '#767872',
        'primary-container': '#fdfbf7',
        'surface-container': '#f0eded',
        'secondary-container': '#fed3c7',
        'secondary': '#77574d',
        'surface-container-highest': '#e4e2e1',
        'surface-variant': '#e4e2e1',
        'surface-bright': '#fcf9f8',
        'on-tertiary-fixed-variant': '#3a4b36',
        'secondary-fixed': '#ffdbd0',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed': '#0f1f0e',
        'on-background': '#1b1c1c',
        'surface-dim': '#dcd9d9',
        'background': '#fcf9f8',
        'on-primary-fixed-variant': '#474744',
        'tertiary-fixed': '#d4e8cc',
        'inverse-on-surface': '#f3f0f0',
        'tertiary': '#51634d',
        'on-secondary-fixed': '#2c160e',
        'on-primary': '#ffffff',
        'tertiary-fixed-dim': '#b8ccb1',
        'surface-container-low': '#f6f3f2',
        'tertiary-container': '#f3ffeb',
        'on-error': '#ffffff',
        'surface-container-high': '#eae7e7',
        'on-tertiary-container': '#667961',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        'element-gap': '24px',
        'section-gap': '120px',
        'gutter': '24px',
        'container-max': '1280px',
      },
      fontFamily: {
        'label-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-xl': ['Playfair Display', 'serif'],
        'headline-xl-mobile': ['Playfair Display', 'serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
        'headline-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-xl-mobile': ['40px', { lineHeight: '1.2', fontWeight: '600' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
